---
name: shop_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  get_it: ^7.2.0
  go_router: ^5.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  internet_connection_checker: ^2.0.0
  connectivity_plus: ^6.0.5
  fluttertoast: ^8.2.5
  loading_animation_widget: ^1.2.1

  path_provider: ^2.1.4
  bloc: ^8.1.2
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  shared_preferences: ^2.1.1
  conditional_builder_null_safety: ^0.0.6
  carousel_slider: ^5.0.0
  font_awesome_flutter: ^10.2.1

  flutter_stripe: ^9.3.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: Inter
    fonts:
    - asset: assets/fonts/Inter_24pt-Medium.ttf
